import { ChangeEvent, useEffect, useState } from "react"
import dataService from '../../../../services/handleRequests'

// Component's interface:
interface tableCell {
    getValue: () => '',
    row: any,
    column: any,
    table: any
}

interface dependencyInterface {
    name: string
    id: string
}

interface directionInterface {
    direccion: string
}

const TableCell: React.FC<tableCell> = ({ getValue, row, column, table }) => {
    const initialValue = getValue()
    const tableMeta = table.options.meta
    const [value, setValue] = useState('')
    const [newValue, setNewValue] = useState<string | null>(null)
    const [departments, setDepartments] = useState([])
    const [directions, setDirections] = useState([])
    
    useEffect(() => {
        setValue(initialValue)
    }, [initialValue])

    const handleSelect = (event: ChangeEvent<HTMLSelectElement>) => {
        setNewValue(event.target.value)
        table.options.meta?.updateData(row.index, column.id, event.target.value)
    }

    const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
        setNewValue(event.target.value)
        table.options.meta?.updateData(row.index, column.id, event.target.value)
    }

    const getDepartments = async () => {
        const token = localStorage.getItem('jwt')
        const deps = await dataService.getDepartments(token)
        const depsValues = deps.map((item: dependencyInterface) => {
            return item.name
        })
        setDepartments(depsValues)
    }

    const getDirections = async () => {
        const token = localStorage.getItem('jwt')
        const dirs = await dataService.getDirections(token)
        const dirValues = dirs.map((item: directionInterface) => {
            return item.direccion
        })
        setDirections(dirValues)
    }

    const handleDirections = (event: ChangeEvent<HTMLSelectElement>) => {
        setNewValue(event.target.value)
        table.options.meta?.updateData(row.index, column.id, event.target.value)
    }

    const userValue = ['USER', 'ADMIN', 'SUPERADMIN']
    const generateUserValue = userValue.filter(item => item !== value)

    // Rendering different inputs depending of the column and the user role:
    if (tableMeta?.newRows[row.id] && column.id === 'departments') {
        getDepartments()
        const generateDependencies = departments.filter(item => item !== value)
        return (
            // Rendering dependencies generated by generateDependencies():
            <select className="items-center py-0.5 pl-1 max-w-fit" onChange={handleSelect}>
                <option value="">{value}</option>
                {
                    generateDependencies.map(item => {
                        return <option key={`dependencyItem${item}`} value={`${item}`}>{item}</option>
                    })
                }
            </select>
        )
    } else if (localStorage.getItem('userRol') === 'SUPERADMIN' && tableMeta?.newRows[row.id] && column.id === 'role') {
        return (
            <select className="items-center py-0.5 pl-1 w-fit" onChange={handleSelect}>
                <option value={value}>{value}</option>
                {
                    generateUserValue.map(item => {
                        return <option key={`userValueItem${item}`} value={`${item}`}>{item}</option>
                    })
                }
            </select>
        )
    } else if (localStorage.getItem('userRol') === 'ADMIN' && tableMeta?.newRows[row.id] && column.id === 'role') {
        return (
            <span>{value}</span>
        )
    } else if (tableMeta?.newRows[row.id] && column.id === 'directions') {
        getDirections()
        const generateDirections = directions.filter(item => item !== value)
        return (
            <select className="items-center py-0.5 pl-1 w-fit" onChange={handleDirections}>
                <option value={value}>{value}</option>
                {
                    generateDirections.map(item => {
                        return <option key={`directionItem${item}`} value={`${item}`}>{item}</option>
                    })
                }
            </select>
        )
    } else if (tableMeta?.newRows[row.id]) {
        return (
            <input
                value={newValue ?? value}
                onChange={handleChange}
                type={column.columnDef.meta?.type || "text"}
                className='items-center py-0.5 px-1 w-[96%] max-w-36'
            />
        )
    }
    return <span>{value}</span>
}

export default TableCell